### PR TITLE
fix: Fixed tooltip positioning w/ increased offset

### LINKED ISSUE #62: Further optimization of category dropdown
@AnninaWalker @ptbrowne do you think we can (find a way) to incoporate the additional text shown below in bold in the dropdown (would need to work for all languages)?

H1: **1-Zimmerwohung**

H2: **2-Zimmerwohnung**

H3: **3-/4-Zimmerwohnung, geringer Verbrauch**

H4: **4-Zimmerwohnung, höherer Verbrauch**

_Originally posted by @sosiology in https://github.com/visualize-admin/electricity-prices-switzerland/issues/55#issuecomment-1403895677_

### LINKED ISSUE #63: Tooltip orientation optimization
The new tooltip on the "Preisverteilung in der Schweiz" chart appears slightly below the bar, as a result, when the values are low, the tooltip points below the x-axis

Image

I would propose adjusting the tooltip so it always pops-up at the top of the bar

### PR DESCRIPTION
**Pull request by noahonyejese**
Closes #63 

This PR improves the tooltip positioning for the histogram Chart by increasing the offset from `10 -> 30`

## How to test

1. Go to this [link](https://elcom-electricity-price-website-git-fix-tooltip-ori-ed2b7e-ixt1.vercel.app/municipality/1402).
2. Scroll down to histograms
3. Hover over the chart
4. See how tooltip is overlapping the smaller bars and is aligned to the top of them ✅ 

## How to reproduce

1. Go to this [link](https://www.strompreis.elcom.admin.ch/municipality/1406)
2. Scroll down to histograms
5. Hover over the chart
6. See how tooltip is overlapping the smaller bars and is not aligned to the top of them ❌ 

---

- [x] I made a self-review of my own code

---

cc: @sosiology

### CODE REVIEW

File: src/components/charts-generic/histogram/histogram-state.tsx [hunk 1]
```diff
@@ -115,7 +121,7 @@ const useHistogramState = ({
       datum: undefined,
       placement: { x: "center", y: "top" },
       xAnchor: xScale((d.x1! + d.x0!) / 2),
-      yAnchor: yScale(getY(d)) + margins.top - 10,
```
Comment (ptbrowne) [inline src/components/charts-generic/histogram/histogram-state.tsx:118]: The 30 seems a bit random, can we have either a constant (I checked if it was = to the tooltip height but no) or figure out really why we need this 30 ? I would like to know the root of the problem :)

Comment (noahonyejese) [reply src/components/charts-generic/histogram/histogram-state.tsx:118]: Do we know why we needed the 10? @ptbrowne

Comment (ptbrowne) [reply src/components/charts-generic/histogram/histogram-state.tsx:118]: No :shrug:

Comment (noahonyejese) [reply src/components/charts-generic/histogram/histogram-state.tsx:118]: Okay I will check

Comment (noahonyejese) [reply src/components/charts-generic/histogram/histogram-state.tsx:118]: @ptbrowne So the `bottom` and `top` ticks are not inbound but outbound each being `14.5 px` twice (bottom and top) = `29px` the bars only cover `0.25 %` of that space making the position of the tooltip offset by `29px * 0.75` = `19.33px` this fixes the tooltip offset and like this the tooltip is perfectly aligned with the bar, however the arrow is not counted, the tooltip arrow is about `8px`. Making our total `8px + 19.33px = 27px` 

I implemented `TOOLTIP_ARROW_HEIGHT` and `TICK_OFFSET` to better communicate this. - let me know if this applicable for you 👍

Comment (ptbrowne) [reply src/components/charts-generic/histogram/histogram-state.tsx:118]: Perfect, thanks 👍

**Review by ptbrowne — APPROVED** [review]
LGTM :+1:
